ALTER TABLE hackathon.marca 
CHANGE COLUMN id id INT NOT NULL AUTO_INCREMENT;
ALTER TABLE hackathon.cor 
CHANGE COLUMN id id INT NOT NULL AUTO_INCREMENT;

ALTER TABLE hackathon.veiculo 
CHANGE COLUMN id id INT NOT NULL AUTO_INCREMENT;

ALTER TABLE hackathon.usuario 
CHANGE COLUMN id id INT NOT NULL AUTO_INCREMENT;

ALTER TABLE veiculo
RENAME COLUMN fotoDestaque TO  fotodestaque;